name: Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - action.yml
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: get-next-version
        uses: thenativeweb/get-next-version@2.6.3
        with:
          prefix: 'v'

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASES_TOKEN }}
          tag_name: ${{ steps.get-next-version.outputs.version }}
          generate_release_notes: true
